fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\Users
  group:
    group_class: App\Entity\Groups
    group_manager: sonata.user.orm.group_manager
  service:
    user_manager: sonata.user.orm.user_manager
  from_email:
    address: "test@example.com"
    sender_name: "test@example.com"